//go:build windows

package main

import (
	_ "embed"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"syscall"
	"time"
	"unsafe"
)

// The same blue download arrow the extension uses, in every size Windows asks
// for. Generated by extension/icons/make_icons.py.
//
//go:embed assets/godm.ico
var iconICO []byte

var (
	shell32 = syscall.NewLazyDLL("shell32.dll")
	ole32   = syscall.NewLazyDLL("ole32.dll")

	procRegisterClassEx    = user32.NewProc("RegisterClassExW")
	procCreateWindowEx     = user32.NewProc("CreateWindowExW")
	procDefWindowProc      = user32.NewProc("DefWindowProcW")
	procGetMessage         = user32.NewProc("GetMessageW")
	procTranslateMessage   = user32.NewProc("TranslateMessage")
	procDispatchMessage    = user32.NewProc("DispatchMessageW")
	procPostMessage        = user32.NewProc("PostMessageW")
	procPostQuitMessage    = user32.NewProc("PostQuitMessage")
	procCreatePopupMenu    = user32.NewProc("CreatePopupMenu")
	procDestroyMenu        = user32.NewProc("DestroyMenu")
	procAppendMenu         = user32.NewProc("AppendMenuW")
	procTrackPopupMenu     = user32.NewProc("TrackPopupMenu")
	procSetForegroundWin   = user32.NewProc("SetForegroundWindow")
	procGetCursorPos       = user32.NewProc("GetCursorPos")
	procRegisterWindowMsg  = user32.NewProc("RegisterWindowMessageW")
	procLoadImage          = user32.NewProc("LoadImageW")
	procGetSystemMetrics   = user32.NewProc("GetSystemMetrics")
	procFindWindow         = user32.NewProc("FindWindowW")
	procShowWindowTray     = user32.NewProc("ShowWindow")
	procSetProcessDPIAware = user32.NewProc("SetProcessDPIAware")
	procSetTimer           = user32.NewProc("SetTimer")
	procSendMessage        = user32.NewProc("SendMessageW")

	procShellNotifyIcon = shell32.NewProc("Shell_NotifyIconW")
	procSHBrowseFolder  = shell32.NewProc("SHBrowseForFolderW")
	procSHGetPath       = shell32.NewProc("SHGetPathFromIDListW")

	procCoInitializeEx = ole32.NewProc("CoInitializeEx")
	procCoTaskMemFree  = ole32.NewProc("CoTaskMemFree")
)

const (
	wmDestroy = 0x0002
	wmCommand = 0x0111
	wmTimer   = 0x0113
	wmUser    = 0x0400
	wmApp     = 0x8000

	wmTrayCallback = wmApp + 1 // mouse events on the icon
	wmTrayEvent    = wmApp + 2 // Go side queued a notification
	wmTrayBrowse   = wmApp + 3 // Go side wants the folder picker

	ninBalloonUserClick = wmUser + 5

	nimAdd    = 0x0
	nimModify = 0x1
	nimDelete = 0x2

	nifMessage = 0x01
	nifIcon    = 0x02
	nifTip     = 0x04
	nifInfo    = 0x10

	niifInfo     = 0x1
	niifNoSound  = 0x10
	imageIcon    = 1
	loadFromFile = 0x0010
	smCXSmIcon   = 49
	smCYSmIcon   = 50

	swRestore = 9

	mfString    = 0x0000
	mfSeparator = 0x0800
	mfChecked   = 0x0008
	mfDefault   = 0x1000

	tpmRightButton = 0x0002
	tpmReturnCmd   = 0x0100

	wsOverlapped = 0x00000000

	bifReturnOnlyFSDirs = 0x0001
	bifEditBox          = 0x0010
	bifNewDialogStyle   = 0x0040
	bffmInitialized     = 1
	bffmSetSelectionW   = wmUser + 103
)

const (
	menuOpen = iota + 1
	menuPauseAll
	menuResumeAll
	menuFolder
	menuNotify
	menuQuit
)

type notifyIconData struct {
	CbSize           uint32
	HWnd             uintptr
	UID              uint32
	UFlags           uint32
	UCallbackMessage uint32
	HIcon            uintptr
	SzTip            [128]uint16
	DwState          uint32
	DwStateMask      uint32
	SzInfo           [256]uint16
	UVersion         uint32
	SzInfoTitle      [64]uint16
	DwInfoFlags      uint32
	GuidItem         [16]byte
	HBalloonIcon     uintptr
}

type wndClassEx struct {
	Size       uint32
	Style      uint32
	WndProc    uintptr
	ClsExtra   int32
	WndExtra   int32
	Instance   uintptr
	Icon       uintptr
	Cursor     uintptr
	Background uintptr
	MenuName   *uint16
	ClassName  *uint16
	IconSm     uintptr
}

type winMsg struct {
	HWnd     uintptr
	Message  uint32
	WParam   uintptr
	LParam   uintptr
	Time     uint32
	Pt       struct{ X, Y int32 }
	LPrivate uint32
}

type browseInfo struct {
	Owner       uintptr
	Root        uintptr
	DisplayName *uint16
	Title       *uint16
	Flags       uint32
	_           uint32
	Callback    uintptr
	LParam      uintptr
	Image       int32
	_           int32
}

type trayNote struct {
	title, text string
	open        string // file to reveal when the notification is clicked, or "app"
}

type browseRequest struct {
	current string
	reply   chan string
}

type tray struct {
	mgr  *Manager
	hwnd uintptr
	nid  notifyIconData

	mu      sync.Mutex
	notes   []trayNote
	pending string // what a click on the current balloon opens

	browse chan browseRequest
}

var theTray struct {
	mu sync.Mutex
	t  *tray
}

// startTray puts godm in the notification area for as long as the daemon runs.
// It owns a message loop on its own OS thread, which is also the thread the
// folder picker has to run on.
func startTray(m *Manager) {
	t := &tray{mgr: m, browse: make(chan browseRequest, 4)}
	theTray.mu.Lock()
	theTray.t = t
	theTray.mu.Unlock()

	go func() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		if err := t.run(); err != nil {
			log.Printf("tray icon unavailable: %v", err)
			theTray.mu.Lock()
			theTray.t = nil
			theTray.mu.Unlock()
		}
	}()
}

func utf16(s string) *uint16 {
	p, err := syscall.UTF16PtrFromString(s)
	if err != nil {
		p, _ = syscall.UTF16PtrFromString("")
	}
	return p
}

func copyUTF16(dst []uint16, s string) {
	src := syscall.StringToUTF16(s)
	if len(src) > len(dst) {
		src = src[:len(dst)]
		src[len(src)-1] = 0
	}
	for i := range dst {
		if i < len(src) {
			dst[i] = src[i]
		} else {
			dst[i] = 0
		}
	}
}

func (t *tray) run() error {
	procSetProcessDPIAware.Call() // so a 150% display gets a crisp 24px icon
	procCoInitializeEx.Call(0, 2) // apartment threaded, for COM below

	// Windows drops notifications from a program it cannot identify, so claim
	// an AppUserModelID and make sure the matching Start menu shortcut exists.
	setAppID()
	if err := ensureStartMenuShortcut(); err != nil {
		log.Printf("start menu shortcut: %v", err)
	}

	className := utf16("godmTrayWindow")
	wc := wndClassEx{
		Size:      uint32(unsafe.Sizeof(wndClassEx{})),
		WndProc:   syscall.NewCallback(trayWndProc),
		ClassName: className,
	}
	if atom, _, err := procRegisterClassEx.Call(uintptr(unsafe.Pointer(&wc))); atom == 0 {
		return fmt.Errorf("register window class: %v", err)
	}
	hwnd, _, err := procCreateWindowEx.Call(0, uintptr(unsafe.Pointer(className)),
		uintptr(unsafe.Pointer(utf16("godm"))), wsOverlapped, 0, 0, 0, 0, 0, 0, 0, 0)
	if hwnd == 0 {
		return fmt.Errorf("create window: %v", err)
	}
	t.hwnd = hwnd

	icon, err := t.loadIcon()
	if err != nil {
		log.Printf("tray icon image: %v", err)
	}

	t.nid = notifyIconData{
		CbSize:           uint32(unsafe.Sizeof(notifyIconData{})),
		HWnd:             hwnd,
		UID:              1,
		UFlags:           nifMessage | nifIcon | nifTip,
		UCallbackMessage: wmTrayCallback,
		HIcon:            icon,
	}
	copyUTF16(t.nid.SzTip[:], "godm")
	if ok, _, err := procShellNotifyIcon.Call(nimAdd, uintptr(unsafe.Pointer(&t.nid))); ok == 0 {
		return fmt.Errorf("add tray icon: %v", err)
	}
	log.Printf("tray icon added")

	procSetTimer.Call(hwnd, 1, 2000, 0) // tooltip refresh
	taskbarCreated, _, _ := procRegisterWindowMsg.Call(uintptr(unsafe.Pointer(utf16("TaskbarCreated"))))

	var msg winMsg
	for {
		ret, _, _ := procGetMessage.Call(uintptr(unsafe.Pointer(&msg)), 0, 0, 0)
		if int32(ret) <= 0 {
			break
		}
		if msg.Message == uint32(taskbarCreated) {
			procShellNotifyIcon.Call(nimAdd, uintptr(unsafe.Pointer(&t.nid)))
			continue
		}
		t.handle(msg)
		procTranslateMessage.Call(uintptr(unsafe.Pointer(&msg)))
		procDispatchMessage.Call(uintptr(unsafe.Pointer(&msg)))
	}
	procShellNotifyIcon.Call(nimDelete, uintptr(unsafe.Pointer(&t.nid)))
	return nil
}

// trayWndProc only needs to pass everything through; the loop above inspects
// messages before dispatching them.
func trayWndProc(hwnd, msg, wparam, lparam uintptr) uintptr {
	ret, _, _ := procDefWindowProc.Call(hwnd, msg, wparam, lparam)
	return ret
}

// iconFile keeps the .ico on disk, where both LoadImage and the Start menu
// shortcut can point at it.
func iconFile() string {
	path := filepath.Join(configDir(), "godm.ico")
	if fi, err := os.Stat(path); err != nil || fi.Size() != int64(len(iconICO)) {
		os.WriteFile(path, iconICO, 0o644)
	}
	return path
}

func (t *tray) loadIcon() (uintptr, error) {
	path := iconFile()
	cx, _, _ := procGetSystemMetrics.Call(smCXSmIcon)
	cy, _, _ := procGetSystemMetrics.Call(smCYSmIcon)
	h, _, err := procLoadImage.Call(0, uintptr(unsafe.Pointer(utf16(path))), imageIcon, cx, cy, loadFromFile)
	if h == 0 {
		return 0, fmt.Errorf("load %s: %v", path, err)
	}
	return h, nil
}

func (t *tray) handle(msg winMsg) {
	switch msg.Message {
	case wmTimer:
		t.updateTooltip()
	case wmTrayEvent:
		t.showQueuedNote()
	case wmTrayBrowse:
		t.serveBrowse()
	case wmTrayCallback:
		switch uint32(msg.LParam) {
		case 0x0202: // WM_LBUTTONUP
			openAppWindow()
		case 0x0205, 0x007B: // WM_RBUTTONUP, WM_CONTEXTMENU
			t.showMenu()
		case ninBalloonUserClick:
			t.mu.Lock()
			open := t.pending
			t.mu.Unlock()
			if open == "" || open == "app" {
				openAppWindow()
			} else {
				showInFolder(open)
			}
		}
	}
}

func (t *tray) updateTooltip() {
	running, queued := 0, 0
	var speed int64
	for _, v := range t.mgr.List() {
		switch v.State {
		case StateRunning:
			running++
			speed += v.Speed
		case StateQueued:
			queued++
		}
	}
	tip := "godm — idle"
	if running > 0 {
		tip = fmt.Sprintf("godm — %d downloading · %s/s", running, humanBytes(speed))
		if queued > 0 {
			tip += fmt.Sprintf(" · %d waiting", queued)
		}
	} else if queued > 0 {
		tip = fmt.Sprintf("godm — %d waiting", queued)
	}
	copyUTF16(t.nid.SzTip[:], tip)
	t.nid.UFlags = nifMessage | nifIcon | nifTip
	procShellNotifyIcon.Call(nimModify, uintptr(unsafe.Pointer(&t.nid)))
}

// notify queues a balloon; the message loop shows it.
func (t *tray) notify(n trayNote) {
	t.mu.Lock()
	t.notes = append(t.notes, n)
	t.mu.Unlock()
	procPostMessage.Call(t.hwnd, wmTrayEvent, 0, 0)
}

func (t *tray) showQueuedNote() {
	t.mu.Lock()
	if len(t.notes) == 0 {
		t.mu.Unlock()
		return
	}
	n := t.notes[0]
	t.notes = t.notes[1:]
	more := len(t.notes)
	t.pending = n.open
	t.mu.Unlock()

	text := n.text
	if more > 0 {
		text += fmt.Sprintf("\n(+%d more)", more)
	}
	copyUTF16(t.nid.SzInfoTitle[:], n.title)
	copyUTF16(t.nid.SzInfo[:], text)
	t.nid.DwInfoFlags = niifInfo
	t.nid.UFlags = nifMessage | nifIcon | nifTip | nifInfo
	procShellNotifyIcon.Call(nimModify, uintptr(unsafe.Pointer(&t.nid)))

	if more > 0 {
		// Give the shell a moment before replacing this balloon with the next.
		go func() {
			time.Sleep(6 * time.Second)
			procPostMessage.Call(t.hwnd, wmTrayEvent, 0, 0)
		}()
	}
}

func (t *tray) showMenu() {
	menu, _, _ := procCreatePopupMenu.Call()
	if menu == 0 {
		return
	}
	defer procDestroyMenu.Call(menu)

	notifyFlag := uintptr(mfString)
	if t.mgr.Notifications() {
		notifyFlag |= mfChecked
	}
	procAppendMenu.Call(menu, mfString|mfDefault, menuOpen, uintptr(unsafe.Pointer(utf16("Open godm"))))
	procAppendMenu.Call(menu, mfSeparator, 0, 0)
	procAppendMenu.Call(menu, mfString, menuPauseAll, uintptr(unsafe.Pointer(utf16("Pause all"))))
	procAppendMenu.Call(menu, mfString, menuResumeAll, uintptr(unsafe.Pointer(utf16("Resume all"))))
	procAppendMenu.Call(menu, mfString, menuFolder, uintptr(unsafe.Pointer(utf16("Open downloads folder"))))
	procAppendMenu.Call(menu, mfSeparator, 0, 0)
	procAppendMenu.Call(menu, notifyFlag, menuNotify, uintptr(unsafe.Pointer(utf16("Notify when downloads finish"))))
	procAppendMenu.Call(menu, mfSeparator, 0, 0)
	procAppendMenu.Call(menu, mfString, menuQuit, uintptr(unsafe.Pointer(utf16("Quit godm"))))

	var pt struct{ X, Y int32 }
	procGetCursorPos.Call(uintptr(unsafe.Pointer(&pt)))
	// Required so the menu closes when the user clicks elsewhere.
	procSetForegroundWin.Call(t.hwnd)
	cmd, _, _ := procTrackPopupMenu.Call(menu, tpmRightButton|tpmReturnCmd,
		uintptr(pt.X), uintptr(pt.Y), 0, t.hwnd, 0)
	procPostMessage.Call(t.hwnd, 0, 0, 0)

	switch cmd {
	case menuOpen:
		openAppWindow()
	case menuPauseAll:
		go t.mgr.PauseAll()
	case menuResumeAll:
		go t.mgr.ResumeAll()
	case menuFolder:
		showInFolder(t.mgr.outDir)
	case menuNotify:
		t.mgr.SetNotifications(!t.mgr.Notifications())
	case menuQuit:
		log.Printf("quit requested from the tray")
		t.mgr.PauseAll()
		t.mgr.save()
		procShellNotifyIcon.Call(nimDelete, uintptr(unsafe.Pointer(&t.nid)))
		os.Exit(0)
	}
}

// openAppWindow brings the manager window up, starting it if it is not open.
func openAppWindow() {
	if h, _, _ := procFindWindow.Call(0, uintptr(unsafe.Pointer(utf16("godm")))); h != 0 {
		procShowWindowTray.Call(h, swRestore)
		procSetForegroundWin.Call(h)
		return
	}
	exe, err := os.Executable()
	if err != nil {
		return
	}
	if err := spawnApp(exe); err != nil {
		log.Printf("could not open the manager window: %v", err)
	}
}

// ---------- folder picker ----------

// browseFolder shows the native folder chooser and returns the chosen path.
// It has to run on the thread owning the message loop, so the request is
// handed to it and the answer comes back on a channel.
func browseFolder(current string) (string, error) {
	theTray.mu.Lock()
	t := theTray.t
	theTray.mu.Unlock()
	if t == nil || t.hwnd == 0 {
		return "", fmt.Errorf("no window is available to show the folder chooser")
	}
	req := browseRequest{current: current, reply: make(chan string, 1)}
	select {
	case t.browse <- req:
	default:
		return "", fmt.Errorf("a folder chooser is already open")
	}
	procPostMessage.Call(t.hwnd, wmTrayBrowse, 0, 0)
	select {
	case path := <-req.reply:
		return path, nil
	case <-time.After(3 * time.Minute):
		return "", fmt.Errorf("the folder chooser timed out")
	}
}

func (t *tray) serveBrowse() {
	var req browseRequest
	select {
	case req = <-t.browse:
	default:
		return
	}
	req.reply <- pickFolder(t.hwnd, req.current)
}

var browseCallback = syscall.NewCallback(func(hwnd, msg, lparam, data uintptr) uintptr {
	if msg == bffmInitialized && data != 0 {
		procSendMessage.Call(hwnd, bffmSetSelectionW, 1, data)
	}
	return 0
})

func pickFolder(owner uintptr, current string) string {
	var display [260]uint16
	bi := browseInfo{
		Owner:       owner,
		DisplayName: &display[0],
		Title:       utf16("Save downloads to"),
		Flags:       bifReturnOnlyFSDirs | bifNewDialogStyle | bifEditBox,
		Callback:    browseCallback,
	}
	if current != "" {
		bi.LParam = uintptr(unsafe.Pointer(utf16(current)))
	}
	pidl, _, _ := procSHBrowseFolder.Call(uintptr(unsafe.Pointer(&bi)))
	if pidl == 0 {
		return ""
	}
	defer procCoTaskMemFree.Call(pidl)
	var buf [260]uint16
	if ok, _, _ := procSHGetPath.Call(pidl, uintptr(unsafe.Pointer(&buf[0]))); ok == 0 {
		return ""
	}
	return syscall.UTF16ToString(buf[:])
}

// trayNotify is what the daemon calls when a download reaches a state worth
// telling the user about.
func trayNotify(title, text, open string) {
	theTray.mu.Lock()
	t := theTray.t
	theTray.mu.Unlock()
	if t == nil || t.hwnd == 0 {
		return
	}
	t.notify(trayNote{title: title, text: text, open: open})
}
